# Marshall Fire constants — generated by prepare_data.jl
using Dates

const WIND_TIMES = [DateTime("2021-12-30T17:00:00"), DateTime("2021-12-30T18:00:00"), DateTime("2021-12-30T19:00:00")]
const EXTENT = (X=(-105.233, -105.131), Y=(39.929, 39.986))
const IGNITION_POINT = (lon=-105.231, lat=39.955)
const M_PER_DEG_LAT = 111_320.0
const M_PER_DEG_LON = 111_320.0 * cosd(40.0)
