#--------------------------------------------------------------------------------# Marshall Fire Data Preparation
#
# Run once in the MarshallWildfire environment to extract and save lightweight data files.
#
#   cd /Users/joshday/.julia/dev/MarshallWildfire
#   julia --project -e 'include("/Users/joshday/.julia/dev/Wildfires/docs/data/marshall/prepare_data.jl")'
#
# Outputs (~2-3 MB total, committed to Wildfires repo):
#   slope.tif, aspect.tif, fuel.tif, elevation.tif  — LANDFIRE bands
#   wind_u_HH.tif, wind_v_HH.tif                    — HRRR u/v wind for hours 17-19 UTC
#   perimeter.geojson                                — observed fire perimeter
#   manifest.jl                                      — constants for the simulation
#--------------------------------------------------------------------------------

using MarshallWildfire
using Rasters, Dates

const OUTDIR = joinpath(@__DIR__)
mkpath(OUTDIR)

#--------------------------------------------------------------------------------# LANDFIRE bands
@info "Extracting LANDFIRE bands..."
landfire = MarshallWildfire.get_landfire_data()

band_map = Dict(
    "slope"     => :US_SLPD2020,
    "aspect"    => :US_ASP2020,
    "fuel"      => :US_250FBFM13,
    "elevation" => :US_ELEV2020,
)

for (name, key) in band_map
    outpath = joinpath(OUTDIR, "$name.tif")
    r = landfire[key]
    # Convert to Float64 to drop Missing union
    r_clean = rebuild(Raster(Float64.(coalesce.(r, NaN)); dims=dims(r), crs=crs(r)))
    write(outpath, r_clean; force=true)
    @info "  Wrote $name.tif ($(size(r_clean)))"
end

#--------------------------------------------------------------------------------# HRRR wind data (hours 17-19 UTC)
@info "Extracting HRRR wind snapshots..."
hrrr = MarshallWildfire.get_hrrr_data()

wind_hours = [17, 18, 19]
wind_times = [DateTime(2021, 12, 30, h) for h in wind_hours]

for (h, t) in zip(wind_hours, wind_times)
    for band in [:u, :v]
        slice = hrrr[Band=At(band), Ti=At(t)]
        outpath = joinpath(OUTDIR, "wind_$(band)_$(lpad(h, 2, '0')).tif")
        write(outpath, slice; force=true)
        @info "  Wrote wind_$(band)_$(lpad(h, 2, '0')).tif ($(size(slice)))"
    end
end

#--------------------------------------------------------------------------------# Perimeter
@info "Copying perimeter..."
src_perimeter = joinpath(dirname(dirname(pathof(MarshallWildfire))), "data", "perimeter.geojson")
dst_perimeter = joinpath(OUTDIR, "perimeter.geojson")
cp(src_perimeter, dst_perimeter; force=true)
@info "  Wrote perimeter.geojson"

#--------------------------------------------------------------------------------# Manifest
@info "Writing manifest.jl..."
manifest = """
# Marshall Fire constants — generated by prepare_data.jl
using Dates

const WIND_TIMES = [DateTime("2021-12-30T17:00:00"), DateTime("2021-12-30T18:00:00"), DateTime("2021-12-30T19:00:00")]
const EXTENT = (X=(-105.233, -105.131), Y=(39.929, 39.986))
const IGNITION_POINT = (lon=-105.231, lat=39.955)
const M_PER_DEG_LAT = 111_320.0
const M_PER_DEG_LON = 111_320.0 * cosd(40.0)
"""
write(joinpath(OUTDIR, "manifest.jl"), manifest)
@info "  Wrote manifest.jl"

@info "Done! Data files saved to $OUTDIR"
